In [1]:
import pandas as pd
import numpy as np
from mnist.loader import MNIST
import timeit

start = timeit.default_timer()

mnist_input_data_path = "C:/Users/Joseph Hwang/Desktop/MNIST/MNIST_data"
mndata = MNIST(mnist_input_data_path)
train_images, train_labels = mndata.load_training()

label_index = 1
combined_slopes = pd.DataFrame([])

for z in range(1, 101):
    with open("C:/Users/Joseph Hwang/Desktop/Sample_Output_Practice/" + str(z) + ".out") as infile:
        for i in range(36):
            next(infile)
        for line in infile:
            sourcefile = infile.read()
    sourcefile_list = sourcefile.split("\n")
    
    y = 0
    edge_weights = []
    df = pd.DataFrame([])
    time = sourcefile_list[0][131:]
    
    for x in range(len(sourcefile_list)): 
        if "Edge From Node" in sourcefile_list[x]:
            if time in sourcefile_list[x][131:] and sourcefile_list[x][90:114] != "":
                edge_weights.append(float(sourcefile_list[x][90:114]))
            elif sourcefile_list[x][90:114] != "":
                df.insert(loc=y, column=time, value=edge_weights)
                edge_weights.clear()
                time = sourcefile_list[x][131:]
                edge_weights.append(float(sourcefile_list[x][90:114]))
                y+=1
    df.insert(loc=y, column=time, value=edge_weights)
    
    df = df.T
    x = np.array(df.index).astype(float)
    slope = []
    
    for z in range(len(df.columns)):
        y = np.array(df[z])
        m, b = np.polyfit(x, y, 1)
        slope.append(m)
    slope.append("Label " + str(train_labels[label_index]))
    label_index+=1
    
    df3 = pd.DataFrame([])
    df3.insert(loc=0, column="slope", value=slope)
    df3 = df3.T
    combined_slopes = combined_slopes.append(df3)    
    
stop = timeit.default_timer()
print('Time: ', stop - start)  

Time:  4.6504384000000005


In [2]:
X = combined_slopes.iloc[:, :-1].values
y = combined_slopes.iloc[:, 90].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[6 0 0 0 0 0 0 0 0 0]
 [0 6 0 0 1 1 0 0 0 1]
 [2 0 0 0 0 0 0 0 1 0]
 [2 0 0 0 0 0 1 0 0 1]
 [1 1 0 1 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 1 0]
 [1 2 0 0 0 0 0 0 1 0]
 [0 0 2 0 0 0 0 0 1 0]
 [1 1 0 1 0 0 0 0 0 0]]
Classification Report:
              precision    recall  f1-score   support

     Label 0       0.43      1.00      0.60         6
     Label 1       0.60      0.67      0.63         9
     Label 2       0.00      0.00      0.00         3
     Label 3       0.00      0.00      0.00         4
     Label 4       0.00      0.00      0.00         3
     Label 5       0.00      0.00      0.00         2
     Label 6       0.50      0.33      0.40         3
     Label 7       0.00      0.00      0.00         4
     Label 8       0.25      0.33      0.29         3
     Label 9       0.00      0.00      0.00         3

    accuracy                           0.35        40
   macro avg       0.18      0.23      0.19        40
weighted avg       0.26 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [3]:
import pandas as pd
import numpy as np
from mnist.loader import MNIST

mnist_input_data_path = "C:/Users/Joseph Hwang/Desktop/MNIST/MNIST_data"
mndata = MNIST(mnist_input_data_path)
train_images, train_labels = mndata.load_training()

label_index = 0
combined_slopes = pd.DataFrame([])
combined_intercepts = pd.DataFrame([])

for z in range(0, 101):
    with open("C:/Users/Joseph Hwang/Desktop/Sample_Output_Practice/Sample_Output_1/" + str(z) + ".out") as infile:
        for i in range(36):
            next(infile)
        for line in infile:
            sourcefile = infile.read()
    sourcefile_list = sourcefile.split("\n")
    
    y = 0
    edge_weights = []
    df = pd.DataFrame([])
    time = sourcefile_list[0][131:]
    
    for x in range(len(sourcefile_list)): 
        if "Edge From Node" in sourcefile_list[x]:
            if time in sourcefile_list[x][131:] and sourcefile_list[x][90:114] != "":
                edge_weights.append(float(sourcefile_list[x][90:114]))
            elif sourcefile_list[x][90:114] != "":
                df.insert(loc=y, column=time, value=edge_weights)
                edge_weights.clear()
                time = sourcefile_list[x][131:]
                edge_weights.append(float(sourcefile_list[x][90:114]))
                y+=1
    df.insert(loc=y, column=time, value=edge_weights)
    
    df = df.T
    x = np.array(df.index).astype(float)
    slope = []
    intercept = []
    
    for z in range(len(df.columns)):
        y = np.array(df[z])
        m, b = np.polyfit(x, y, 1)
        slope.append(m)
        intercept.append(b)
    slope.append("Label " + str(train_labels[label_index]))
    intercept.append("Label " + str(train_labels[label_index]))
    label_index+=1
    
    df3 = pd.DataFrame([])
    df3.insert(loc=0, column="slope", value=slope)
    df3 = df3.T
    
    df4 = pd.DataFrame([])
    df4.insert(loc=0, column="intercept", value=intercept)
    df4 = df4.T
    
    combined_slopes = combined_slopes.append(df3)    
    combined_intercepts = combined_intercepts.append(df4)

In [6]:
X = combined_slopes.iloc[:, :-1].values
y = combined_slopes.iloc[:, 9900].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5)
classifier.fit(X_train, y_train)

y_pred = classifier.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[1 0 0 0 1 0 0 1 2 0]
 [0 6 0 1 0 0 0 2 0 1]
 [0 0 0 0 0 0 2 0 0 0]
 [1 0 0 1 0 0 1 1 1 0]
 [0 0 0 0 1 0 0 1 0 2]
 [0 0 0 1 0 0 0 2 0 0]
 [0 0 0 0 1 0 2 0 0 0]
 [0 2 0 0 0 0 0 0 0 1]
 [0 0 0 0 2 0 1 0 0 1]
 [0 0 0 0 1 0 0 0 0 1]]
Classification Report:
              precision    recall  f1-score   support

     Label 0       0.50      0.20      0.29         5
     Label 1       0.75      0.60      0.67        10
     Label 2       0.00      0.00      0.00         2
     Label 3       0.33      0.20      0.25         5
     Label 4       0.17      0.25      0.20         4
     Label 5       0.00      0.00      0.00         3
     Label 6       0.33      0.67      0.44         3
     Label 7       0.00      0.00      0.00         3
     Label 8       0.00      0.00      0.00         4
     Label 9       0.17      0.50      0.25         2

    accuracy                           0.29        41
   macro avg       0.22      0.24      0.21        41
weighted avg       0.33 

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [7]:
X = combined_slopes.iloc[:, :4950].values
y = combined_slopes.iloc[:, 4950].values

from sklearn.neighbors import KNeighborsRegressor
knnr = KNeighborsRegressor(n_neighbors = 5)

knnr.fit(X, y)
print ("The MSE is:",format(np.power(y-knnr.predict(X),2).mean()))

The MSE is: 5.5662025465081555e-09
